REM INSERTING into FINALPROJECT.TB_SCR
SET DEFINE OFF;
Insert into FINALPROJECT.TB_SCR (EXAM_ID,STDT_NO,SBJT_NM,SCORE) values ('EX0001','S1','국어',80);
Insert into FINALPROJECT.TB_SCR (EXAM_ID,STDT_NO,SBJT_NM,SCORE) values ('EX0001','S1','영어',68);
Insert into FINALPROJECT.TB_SCR (EXAM_ID,STDT_NO,SBJT_NM,SCORE) values ('EX0001','S1','수학',90);
Insert into FINALPROJECT.TB_SCR (EXAM_ID,STDT_NO,SBJT_NM,SCORE) values ('EX0001','S1','사회',86);
Insert into FINALPROJECT.TB_SCR (EXAM_ID,STDT_NO,SBJT_NM,SCORE) values ('EX0001','S1','과학',79);
Insert into FINALPROJECT.TB_SCR (EXAM_ID,STDT_NO,SBJT_NM,SCORE) values ('EX001','S1','영어',87);
Insert into FINALPROJECT.TB_SCR (EXAM_ID,STDT_NO,SBJT_NM,SCORE) values ('EX001','S1','수학',66);
Insert into FINALPROJECT.TB_SCR (EXAM_ID,STDT_NO,SBJT_NM,SCORE) values ('EX001','S1','사회',99);
Insert into FINALPROJECT.TB_SCR (EXAM_ID,STDT_NO,SBJT_NM,SCORE) values ('EX001','S1','국어',87);
Insert into FINALPROJECT.TB_SCR (EXAM_ID,STDT_NO,SBJT_NM,SCORE) values ('EX001','S1','과학',90);
Insert into FINALPROJECT.TB_SCR (EXAM_ID,STDT_NO,SBJT_NM,SCORE) values ('EX002','S1','영어',77);
Insert into FINALPROJECT.TB_SCR (EXAM_ID,STDT_NO,SBJT_NM,SCORE) values ('EX002','S1','수학',79);
Insert into FINALPROJECT.TB_SCR (EXAM_ID,STDT_NO,SBJT_NM,SCORE) values ('EX002','S1','사회',87);
Insert into FINALPROJECT.TB_SCR (EXAM_ID,STDT_NO,SBJT_NM,SCORE) values ('EX002','S1','국어',94);
Insert into FINALPROJECT.TB_SCR (EXAM_ID,STDT_NO,SBJT_NM,SCORE) values ('EX002','S1','과학',100);
Insert into FINALPROJECT.TB_SCR (EXAM_ID,STDT_NO,SBJT_NM,SCORE) values ('EX002','S7','영어',40);
Insert into FINALPROJECT.TB_SCR (EXAM_ID,STDT_NO,SBJT_NM,SCORE) values ('EX003','S6','수학',53);
