REM INSERTING into FINALPROJECT.TB_SBJT
SET DEFINE OFF;
Insert into FINALPROJECT.TB_SBJT (SBJT_NM,WEIGHT) values ('수학',2);
Insert into FINALPROJECT.TB_SBJT (SBJT_NM,WEIGHT) values ('영어',2);
Insert into FINALPROJECT.TB_SBJT (SBJT_NM,WEIGHT) values ('국어',2);
Insert into FINALPROJECT.TB_SBJT (SBJT_NM,WEIGHT) values ('과학',1);
Insert into FINALPROJECT.TB_SBJT (SBJT_NM,WEIGHT) values ('사회',1);
Insert into FINALPROJECT.TB_SBJT (SBJT_NM,WEIGHT) values ('전과목',0);
