--------------------------------------------------------
--  Constraints for Table TB_ATTND
--------------------------------------------------------

  ALTER TABLE "FINALPROJECT"."TB_ATTND" ADD CONSTRAINT "PK_TB_ATTND" PRIMARY KEY ("DT", "TM", "ATTND_TP", "CLSS_ID", "STDT_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FINALPROJECT"."TB_ATTND" MODIFY ("STDT_NO" NOT NULL ENABLE);
  ALTER TABLE "FINALPROJECT"."TB_ATTND" MODIFY ("CLSS_ID" NOT NULL ENABLE);
  ALTER TABLE "FINALPROJECT"."TB_ATTND" MODIFY ("ATTND_TP" NOT NULL ENABLE);
  ALTER TABLE "FINALPROJECT"."TB_ATTND" MODIFY ("TM" NOT NULL ENABLE);
  ALTER TABLE "FINALPROJECT"."TB_ATTND" MODIFY ("DT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TB_CD
--------------------------------------------------------

  ALTER TABLE "FINALPROJECT"."TB_CD" ADD CONSTRAINT "PK_TB_CD" PRIMARY KEY ("CD_TP", "CD_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FINALPROJECT"."TB_CD" MODIFY ("CD_ID" NOT NULL ENABLE);
  ALTER TABLE "FINALPROJECT"."TB_CD" MODIFY ("CD_TP" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TB_CLSS
--------------------------------------------------------

  ALTER TABLE "FINALPROJECT"."TB_CLSS" ADD CONSTRAINT "PK_TB_CLSS" PRIMARY KEY ("CLSS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FINALPROJECT"."TB_CLSS" MODIFY ("CLSS_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TB_CRS
--------------------------------------------------------

  ALTER TABLE "FINALPROJECT"."TB_CRS" ADD CONSTRAINT "PK_TB_CRS" PRIMARY KEY ("CRS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FINALPROJECT"."TB_CRS" MODIFY ("CRS_INTRO" NOT NULL ENABLE);
  ALTER TABLE "FINALPROJECT"."TB_CRS" MODIFY ("DAY_CLSS_TM" NOT NULL ENABLE);
  ALTER TABLE "FINALPROJECT"."TB_CRS" MODIFY ("STDTCLSSTTN" NOT NULL ENABLE);
  ALTER TABLE "FINALPROJECT"."TB_CRS" MODIFY ("CRS_NM" NOT NULL ENABLE);
  ALTER TABLE "FINALPROJECT"."TB_CRS" MODIFY ("CRS_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TB_EMP
--------------------------------------------------------

  ALTER TABLE "FINALPROJECT"."TB_EMP" ADD CONSTRAINT "PK_TB_EMP" PRIMARY KEY ("EMP_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FINALPROJECT"."TB_EMP" MODIFY ("EMP_NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TB_EXAM_TP
--------------------------------------------------------

  ALTER TABLE "FINALPROJECT"."TB_EXAM_TP" ADD CONSTRAINT "PK_TB_EXAM_TP" PRIMARY KEY ("EXAM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FINALPROJECT"."TB_EXAM_TP" MODIFY ("EXAM_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TB_NTC
--------------------------------------------------------

  ALTER TABLE "FINALPROJECT"."TB_NTC" ADD CONSTRAINT "PK_TB_NTC" PRIMARY KEY ("NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FINALPROJECT"."TB_NTC" MODIFY ("DT" NOT NULL ENABLE);
  ALTER TABLE "FINALPROJECT"."TB_NTC" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "FINALPROJECT"."TB_NTC" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "FINALPROJECT"."TB_NTC" MODIFY ("NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TB_PAY_HIST
--------------------------------------------------------

  ALTER TABLE "FINALPROJECT"."TB_PAY_HIST" ADD CONSTRAINT "PK_TB_PAY_HIST" PRIMARY KEY ("EMP_NO", "YEAR_MONTH")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FINALPROJECT"."TB_PAY_HIST" MODIFY ("YEAR_MONTH" NOT NULL ENABLE);
  ALTER TABLE "FINALPROJECT"."TB_PAY_HIST" MODIFY ("EMP_NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TB_QNA
--------------------------------------------------------

  ALTER TABLE "FINALPROJECT"."TB_QNA" ADD CONSTRAINT "PK_TB_QNA" PRIMARY KEY ("NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FINALPROJECT"."TB_QNA" MODIFY ("DT" NOT NULL ENABLE);
  ALTER TABLE "FINALPROJECT"."TB_QNA" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "FINALPROJECT"."TB_QNA" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "FINALPROJECT"."TB_QNA" MODIFY ("NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TB_QZ
--------------------------------------------------------

  ALTER TABLE "FINALPROJECT"."TB_QZ" ADD CONSTRAINT "PK_TB_QZ" PRIMARY KEY ("EXAM_ID", "ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FINALPROJECT"."TB_QZ" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "FINALPROJECT"."TB_QZ" MODIFY ("EXAM_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TB_SALE
--------------------------------------------------------

  ALTER TABLE "FINALPROJECT"."TB_SALE" ADD CONSTRAINT "PK_TB_SALE" PRIMARY KEY ("YEAR", "MONTH", "DAY", "COST_ITEM", "NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FINALPROJECT"."TB_SALE" MODIFY ("NO" NOT NULL ENABLE);
  ALTER TABLE "FINALPROJECT"."TB_SALE" MODIFY ("COST_ITEM" NOT NULL ENABLE);
  ALTER TABLE "FINALPROJECT"."TB_SALE" MODIFY ("DAY" NOT NULL ENABLE);
  ALTER TABLE "FINALPROJECT"."TB_SALE" MODIFY ("MONTH" NOT NULL ENABLE);
  ALTER TABLE "FINALPROJECT"."TB_SALE" MODIFY ("YEAR" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TB_SBJT
--------------------------------------------------------

  ALTER TABLE "FINALPROJECT"."TB_SBJT" ADD CONSTRAINT "PK_TB_SBJT" PRIMARY KEY ("SBJT_NM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FINALPROJECT"."TB_SBJT" MODIFY ("SBJT_NM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TB_SCR
--------------------------------------------------------

  ALTER TABLE "FINALPROJECT"."TB_SCR" ADD CONSTRAINT "PK_TB_SCR" PRIMARY KEY ("EXAM_ID", "STDT_NO", "SBJT_NM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FINALPROJECT"."TB_SCR" MODIFY ("SBJT_NM" NOT NULL ENABLE);
  ALTER TABLE "FINALPROJECT"."TB_SCR" MODIFY ("STDT_NO" NOT NULL ENABLE);
  ALTER TABLE "FINALPROJECT"."TB_SCR" MODIFY ("EXAM_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TB_STDT
--------------------------------------------------------

  ALTER TABLE "FINALPROJECT"."TB_STDT" ADD CONSTRAINT "PK_TB_STDT" PRIMARY KEY ("STDT_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FINALPROJECT"."TB_STDT" MODIFY ("STDT_NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TB_STDTCLSS
--------------------------------------------------------

  ALTER TABLE "FINALPROJECT"."TB_STDTCLSS" ADD CONSTRAINT "PK_TB_STDTCLSS" PRIMARY KEY ("CLSS_ID", "STDT_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FINALPROJECT"."TB_STDTCLSS" MODIFY ("STDT_NO" NOT NULL ENABLE);
  ALTER TABLE "FINALPROJECT"."TB_STDTCLSS" MODIFY ("CLSS_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TB_TCHR
--------------------------------------------------------

  ALTER TABLE "FINALPROJECT"."TB_TCHR" ADD CONSTRAINT "PK_TB_TCHR" PRIMARY KEY ("TCHR_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FINALPROJECT"."TB_TCHR" MODIFY ("TCHR_NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TB_TCHRASSN
--------------------------------------------------------

  ALTER TABLE "FINALPROJECT"."TB_TCHRASSN" ADD CONSTRAINT "PK_TB_TCHRASSN" PRIMARY KEY ("TCHR_NO", "CLSS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FINALPROJECT"."TB_TCHRASSN" MODIFY ("CLSS_ID" NOT NULL ENABLE);
  ALTER TABLE "FINALPROJECT"."TB_TCHRASSN" MODIFY ("TCHR_NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TB_TPC
--------------------------------------------------------

  ALTER TABLE "FINALPROJECT"."TB_TPC" ADD CONSTRAINT "PK_TB_TPC" PRIMARY KEY ("TPC_NM", "SBJT_NM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FINALPROJECT"."TB_TPC" MODIFY ("SBJT_NM" NOT NULL ENABLE);
  ALTER TABLE "FINALPROJECT"."TB_TPC" MODIFY ("TPC_NM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TB_TTLQZ
--------------------------------------------------------

  ALTER TABLE "FINALPROJECT"."TB_TTLQZ" ADD CONSTRAINT "PK_TB_TTLQZ" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FINALPROJECT"."TB_TTLQZ" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TB_USR
--------------------------------------------------------

  ALTER TABLE "FINALPROJECT"."TB_USR" ADD CONSTRAINT "UK_TB_USR" UNIQUE ("PHONE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FINALPROJECT"."TB_USR" ADD CONSTRAINT "PK_TB_USR" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FINALPROJECT"."TB_USR" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "FINALPROJECT"."TB_USR" MODIFY ("ADDR" NOT NULL ENABLE);
  ALTER TABLE "FINALPROJECT"."TB_USR" MODIFY ("PHONE" NOT NULL ENABLE);
  ALTER TABLE "FINALPROJECT"."TB_USR" MODIFY ("NM" NOT NULL ENABLE);
  ALTER TABLE "FINALPROJECT"."TB_USR" MODIFY ("PW" NOT NULL ENABLE);
  ALTER TABLE "FINALPROJECT"."TB_USR" MODIFY ("ID" NOT NULL ENABLE);
