--------------------------------------------------------
--  DDL for Table TB_ATTND
--------------------------------------------------------

  CREATE TABLE "FINALPROJECT"."TB_ATTND" 
   (	"DT" CHAR(8 BYTE), 
	"TM" CHAR(6 BYTE), 
	"ATTND_TP" VARCHAR2(10 BYTE), 
	"CLSS_ID" VARCHAR2(10 BYTE), 
	"STDT_NO" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TB_CD
--------------------------------------------------------

  CREATE TABLE "FINALPROJECT"."TB_CD" 
   (	"CD_TP" VARCHAR2(3 BYTE), 
	"CD_ID" VARCHAR2(10 BYTE), 
	"CD_NM" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TB_CLSS
--------------------------------------------------------

  CREATE TABLE "FINALPROJECT"."TB_CLSS" 
   (	"CLSS_ID" VARCHAR2(10 BYTE), 
	"CRS_ID" VARCHAR2(10 BYTE), 
	"CLSS_NM" VARCHAR2(100 BYTE), 
	"STRT_DT" CHAR(8 BYTE), 
	"END_DT" CHAR(8 BYTE), 
	"STRT_TM" CHAR(6 BYTE), 
	"END_TM" CHAR(6 BYTE), 
	"CAPA" NUMBER, 
	"CLSSROOM" VARCHAR2(2 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TB_CRS
--------------------------------------------------------

  CREATE TABLE "FINALPROJECT"."TB_CRS" 
   (	"CRS_ID" VARCHAR2(10 BYTE), 
	"CRS_NM" VARCHAR2(100 BYTE), 
	"PRD" NUMBER, 
	"STDTCLSSTTN" NUMBER, 
	"DAY_CLSS_TM" NUMBER, 
	"CRS_TP" VARCHAR2(10 BYTE), 
	"CRS_INTRO" VARCHAR2(1024 BYTE), 
	"SBJT_NM" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TB_EMP
--------------------------------------------------------

  CREATE TABLE "FINALPROJECT"."TB_EMP" 
   (	"EMP_NO" VARCHAR2(10 BYTE), 
	"ID" VARCHAR2(10 BYTE), 
	"SLR" NUMBER, 
	"RETIRED_DT" CHAR(8 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TB_EXAM_TP
--------------------------------------------------------

  CREATE TABLE "FINALPROJECT"."TB_EXAM_TP" 
   (	"EXAM_ID" VARCHAR2(10 BYTE), 
	"EXAM_TITLE" VARCHAR2(100 BYTE), 
	"EXAM_DT" CHAR(8 BYTE), 
	"EXAM_TP" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TB_NTC
--------------------------------------------------------

  CREATE TABLE "FINALPROJECT"."TB_NTC" 
   (	"NO" NUMBER, 
	"EMP_NO" VARCHAR2(10 BYTE), 
	"TITLE" VARCHAR2(200 BYTE), 
	"CONTENT" VARCHAR2(1024 BYTE), 
	"ATTCH_FILE" VARCHAR2(100 BYTE), 
	"DT" CHAR(8 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TB_PAY_HIST
--------------------------------------------------------

  CREATE TABLE "FINALPROJECT"."TB_PAY_HIST" 
   (	"EMP_NO" VARCHAR2(10 BYTE), 
	"YEAR_MONTH" CHAR(6 BYTE), 
	"SLR" NUMBER, 
	"PAID_DT" CHAR(8 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TB_QNA
--------------------------------------------------------

  CREATE TABLE "FINALPROJECT"."TB_QNA" 
   (	"NO" NUMBER, 
	"ID" VARCHAR2(10 BYTE), 
	"TITLE" VARCHAR2(50 BYTE), 
	"CONTENT" VARCHAR2(512 BYTE), 
	"DT" CHAR(8 BYTE), 
	"GP_NUM" NUMBER, 
	"SEQ_LV" NUMBER, 
	"SEQ_NUM" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TB_QZ
--------------------------------------------------------

  CREATE TABLE "FINALPROJECT"."TB_QZ" 
   (	"EXAM_ID" VARCHAR2(10 BYTE), 
	"ID" NUMBER, 
	"QUEST_NO" NUMBER, 
	"QUEST_WGT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TB_SALE
--------------------------------------------------------

  CREATE TABLE "FINALPROJECT"."TB_SALE" 
   (	"YEAR" NUMBER, 
	"MONTH" NUMBER, 
	"DAY" NUMBER, 
	"COST_ITEM" VARCHAR2(20 BYTE), 
	"NO" NUMBER, 
	"AMOUNT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TB_SBJT
--------------------------------------------------------

  CREATE TABLE "FINALPROJECT"."TB_SBJT" 
   (	"SBJT_NM" VARCHAR2(20 BYTE), 
	"WEIGHT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TB_SCR
--------------------------------------------------------

  CREATE TABLE "FINALPROJECT"."TB_SCR" 
   (	"EXAM_ID" VARCHAR2(10 BYTE), 
	"STDT_NO" VARCHAR2(10 BYTE), 
	"SBJT_NM" VARCHAR2(20 BYTE), 
	"SCORE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TB_STDT
--------------------------------------------------------

  CREATE TABLE "FINALPROJECT"."TB_STDT" 
   (	"STDT_NO" VARCHAR2(10 BYTE), 
	"ID" VARCHAR2(10 BYTE), 
	"RETRY_CNT" NUMBER, 
	"MJR_TP" VARCHAR2(10 BYTE), 
	"PRNT_PHONE" VARCHAR2(13 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TB_STDTCLSS
--------------------------------------------------------

  CREATE TABLE "FINALPROJECT"."TB_STDTCLSS" 
   (	"CLSS_ID" VARCHAR2(10 BYTE), 
	"STDT_NO" VARCHAR2(10 BYTE), 
	"REPAID_DT" CHAR(8 BYTE), 
	"PAID_DT" CHAR(8 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TB_TCHR
--------------------------------------------------------

  CREATE TABLE "FINALPROJECT"."TB_TCHR" 
   (	"TCHR_NO" VARCHAR2(10 BYTE), 
	"ID" VARCHAR2(10 BYTE), 
	"SBJT_CHRG" VARCHAR2(10 BYTE), 
	"TCHR_INTRO" VARCHAR2(1024 BYTE), 
	"TCHR_PT" VARCHAR2(100 BYTE), 
	"EMP_NO" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TB_TCHRASSN
--------------------------------------------------------

  CREATE TABLE "FINALPROJECT"."TB_TCHRASSN" 
   (	"TCHR_NO" VARCHAR2(10 BYTE), 
	"CLSS_ID" VARCHAR2(10 BYTE), 
	"CHRG" VARCHAR2(2 BYTE), 
	"SLR" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TB_TPC
--------------------------------------------------------

  CREATE TABLE "FINALPROJECT"."TB_TPC" 
   (	"TPC_NM" VARCHAR2(50 BYTE), 
	"SBJT_NM" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TB_TTLQZ
--------------------------------------------------------

  CREATE TABLE "FINALPROJECT"."TB_TTLQZ" 
   (	"ID" NUMBER, 
	"SBJT_NM" VARCHAR2(20 BYTE), 
	"TCHR_NO" VARCHAR2(10 BYTE), 
	"TPC_NM" VARCHAR2(50 BYTE), 
	"TITLE" VARCHAR2(256 BYTE), 
	"CONTENT" VARCHAR2(1024 BYTE), 
	"SOLUTION" VARCHAR2(1024 BYTE), 
	"DEGREE" VARCHAR2(3 BYTE), 
	"ANSWER" VARCHAR2(20 BYTE), 
	"IMG_FILE" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TB_USR
--------------------------------------------------------

  CREATE TABLE "FINALPROJECT"."TB_USR" 
   (	"ID" VARCHAR2(10 BYTE), 
	"PW" VARCHAR2(20 BYTE), 
	"NM" VARCHAR2(20 BYTE), 
	"PHONE" VARCHAR2(13 BYTE), 
	"ADDR" VARCHAR2(100 BYTE), 
	"EMAIL" VARCHAR2(20 BYTE), 
	"USR_TP" VARCHAR2(20 BYTE), 
	"PWS" VARCHAR2(250 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
